<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://ws.pfg.uned" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://ws.pfg.uned" xmlns:intf="http://ws.pfg.uned" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://ws.pfg.uned" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="envioDistribuidores">
    <complexType/>
   </element>
   <element name="envioDistribuidoresResponse">
    <complexType>
     <sequence>
      <element name="envioDistribuidoresReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="envioDistribuidoresResponse">

      <wsdl:part element="impl:envioDistribuidoresResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="envioDistribuidoresRequest">

      <wsdl:part element="impl:envioDistribuidores" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="WS_Distribuidor">

      <wsdl:operation name="envioDistribuidores">

         <wsdl:input message="impl:envioDistribuidoresRequest" name="envioDistribuidoresRequest">

       </wsdl:input>

         <wsdl:output message="impl:envioDistribuidoresResponse" name="envioDistribuidoresResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="WS_DistribuidorSoapBinding" type="impl:WS_Distribuidor">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="envioDistribuidores">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="envioDistribuidoresRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="envioDistribuidoresResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="WS_DistribuidorService">

      <wsdl:port binding="impl:WS_DistribuidorSoapBinding" name="WS_Distribuidor">

         <wsdlsoap:address location="http://localhost:8080/Aplicacion_Web/services/WS_Distribuidor"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
